### ISSUE TITLE
The latest version of ComfyUI reported an error

### ISSUE THREAD

**Issue by laixiao** [ViewComfy/ViewComfy#19]
Perhaps you need to adapt to the latest version of ComfyUI for API export.
=======Error========
Error TypeError: Cannot read properties of undefined (reading 'title')
    at workflowAPItoViewComfy (workflow-api-parser.ts:48:47)
    at reader.onload (view-comfy-page.tsx:51:77)
7workflow-api-parser.ts:89 Error TypeError: Cannot read properties of undefined (reading 'title')
    at workflowAPItoViewComfy (workflow-api-parser.ts:83:40)
    at reader.onload (view-comfy-page.tsx:51:77)
workflow-api-parser.ts:127 Nested object Object
2workflow-api-parser.ts:89 Error TypeError: Cannot read properties of undefined (reading 'title')
    at workflowAPItoViewComfy (workflow-api-parser.ts:83:40)
    at reader.onload (view-comfy-page.tsx:51:77)
workflow-api-parser.ts:89 Error TypeError: Cannot read properties of undefined (reading 'title')
    at workflowAPItoViewComfy (workflow-api-parser.ts:48:47)
    at reader.onload (view-comfy-page.tsx:51:77)
6workflow-api-parser.ts:89 Error TypeError: Cannot read properties of undefined (reading 'title')
    at workflowAPItoViewComfy (workflow-api-parser.ts:83:40)
    at reader.onload (view-comfy-page.tsx:51:77)

**Comment by chinchaun** [comment]
hey @laixiao, I just tried some workflows with the latest ComfyUI version and it's working, can you share an example of the workflow that is not working for you?

**Comment by laixiao** [comment]
[xhs-api.json](https://github.com/user-attachments/files/17531197/xhs-api.json)
[view_comfy.json](https://github.com/user-attachments/files/17531198/view_comfy.json)
thanks, error workflows

**Comment by chinchaun** [comment]
Thank you, I will take a look

**Comment by chinchaun** [comment]
hey @laixiao, I manage to reproduce the error with your files, the nodes didn't have any meta-data and it was breaking the parser, I just pushed a fix, please let me know how it goes

**Comment by laixiao** [comment]
> hey @laixiao, I manage to reproduce the error with your files, the nodes didn't have any meta-data and it was breaking the parser, I just pushed a fix, please let me know how it goes

The issue has been fixed, but it seems that the nodes cannot be named customarily.![image](https://github.com/user-attachments/assets/20974257-ecfa-4aed-9ecc-d0621305cd4f)

**Comment by chinchaun** [comment]
@laixiao, the issue is that in those nodes in ComfyUI you're not adding any information, you can put the title there and it will show up in ViewComfy or you can edit the view_comfy.json by hand

**Comment by laixiao** [comment]
OK, thanks





------------------ Original ------------------
From: Jean Delannoy ***@***.***&gt;
Date: Tue,Oct 29,2024 1:00 AM
To: ViewComfy/ViewComfy ***@***.***&gt;
Cc: laixiao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ViewComfy/ViewComfy] The latest version of ComfyUI reported anerror (Issue #19)





 
@laixiao, the issue is that in those nodes in ComfyUI you're not adding any information, you can put the title there and it will show up in ViewComfy or you can edit the view_comfy.json by hand
