### ISSUE TITLE
Support connection without port

### ISSUE THREAD

**Issue by raonsol** [ViewComfy/ViewComfy#21]
When setting connection info ComfyUI backend in `.env`, I found that current code explicitly set port number to "8188".
This implementation does not support the cases when there is no port number in URL with subpaths. (e.g. exmple.com/comfyui/)

I created pull request to fix this.

**Comment by chinchaun** [comment]
Hey @raonsol, you're right, and thanks for making a PR to fix it. I was thinking about it, and maybe it would be better to remove the necessity to add the PORT in a separate variable and just put the full URL of the Comfy API endpoint, and we can get it off all the edge cases. What do you think?

e.g:

this.apiUrl = process.env.COMFYUI_API_URL || "127.0.0.1:8188";

->

 return `${this.httpBaseUrl}${this.apiUrl}`;

**Comment by raonsol** [comment]
sorry for late reply, I think this is way better.
