### ISSUE TITLE
Load workflow

### ISSUE THREAD

**Issue by LSliu666** [ViewComfy/ViewComfy#25]
Hello, I would like to ask a few questions about loading the workflow
1. How to upload one's own workflow when the page does not display false when NEXT_PULIC_VIEW.MODE="true"
2. How to load multiple workflows, where to place them in view format JSON files or comfyui API JSON files when needed, and how to choose between multiple workflows

**Comment by chinchaun** [comment]
Hello @LSliu666 

> 1. How to upload one's own workflow when the page does not display false when NEXT_PULIC_VIEW.MODE="true"
the purpose of the NEXT_PULIC_VIEW.MODE="true" is to show only the playground UI without the editor by design you're not able to upload any workflow files

> 2. How to load multiple workflows, where to place them in view format JSON files or comfyui API JSON files when needed, and how to choose between multiple workflows.

In the editor, you can upload a workflow, save the changes, and then you can keep uploading more, save them again and in the playground, you will have a dropdown to pick from

**Comment by LSliu666** [comment]
Okay, thank you

**Comment by LSliu666** [comment]
Hello, I tried and it is indeed possible to have multiple workflows, but once the original workflow list is refreshed, it disappears and can only be re uploaded. Is there a way to permanently save the multiple workflow list? Save the workflow in a specific folder?

**Comment by LSliu666** [comment]
@chinchaun

**Comment by LSliu666** [comment]
Also, what should I do if I upload multiple pictures/videos，

**Comment by chinchaun** [comment]
Hey @LSliu666, after you upload all the workflows that you want to use, you can download them "Download as ViewComfy JSON" Then, you can put that in the root of the ViewComfy repo, and it will load it automatically, as you can see in the readme. Let me know how it goes and if something is not clear
