### ISSUE TITLE
Unable to run any workflow

### ISSUE THREAD

**Issue by north151** [ViewComfy/ViewComfy#33]
POST /api/comfy 500 in 283ms
 POST /api/comfy 500 in 8ms
![image](https://github.com/user-attachments/assets/235fee3a-e1a7-4861-b32b-45adb7488c25)

**Comment by chinchaun** [comment]
hello @north151, can you share the output from the terminal where you run the viewcomfy app?

**Comment by chinchaun** [comment]
closing lack of activity
