### ISSUE TITLE
My node-v18.19.0-win-x64 is not running

### ISSUE THREAD

**Issue by laixiao** [ViewComfy/ViewComfy#37]
![image](https://github.com/user-attachments/assets/76200846-1ce0-4079-8d00-cab584c02157)

@since — v20.0.0

My node-v18.19.0-win-x64 is not running

**Comment by chinchaun** [comment]
hey @laixiao, I think the main issue is around NextJS, trying updating Node to v20, you can check it here 

https://github.com/vercel/next.js/discussions/56032
