### ISSUE TITLE
Auto generate random seed for nodes when the value is "randomize"

### ISSUE THREAD

**Issue by chinchaun** [ViewComfy/ViewComfy#46]
We want to reproduce the behavior of the ComfyUI, which auto-generates a random number when a seed input has the value "randomize."
So far, the value of the input of the nodes that we know refers to a seed are ["seed", "noise_seed", "rand_seed"].

In this function, we need to add an else if that check if the class_type === "KSampler" and check in the inputs if the ["seed", "noise_seed", "rand_seed"] values exist and if they have the value randomize, generate a random number

```typescript
  const minCeiled = Math.ceil(0);
  const maxFloored = Math.floor(2**32);
  this.workflow[key].inputs.seed = return Math.floor(Math.random() * (maxFloored - minCeiled + 1) + minCeiled); 
```

https://github.com/ViewComfy/ViewComfy/blob/ec85150955bb2c11ffdad1b2c4a6895d0147b7ab/app/models/comfy-workflow.ts#L41-L45

**Comment by veka-server** [comment]
The requested functionality has been implemented, and a pull request has been submitted : [PR #48](https://github.com/ViewComfy/ViewComfy/pull/48).

**Comment by chinchaun** [comment]
wohooo :partying_face:, this has been merge, thank you very much @veka-server
