### ISSUE TITLE
How to automatically load a saved workflow in a playground?

### ISSUE THREAD

**Issue by Jypope** [ViewComfy/ViewComfy#49]
Whenever I restart viewcomfy, the workflow that was previously in the playground is gone. I'd like to know where I should put the saved workflow.json so that it can automatically load the workflow every time I restart viewcomfy.

**Comment by Jypope** [comment]
I tried to modify the code in .env, as follows:
VIEW_COMFY_FILE_NAME="view_comfy.json"
But this can only load one json, can it load multiple jsons by default?

**Comment by chinchaun** [comment]
Hello @Jypope, you need to put the saved workflow in the root of the viewcomfy project and it will get picked up or you can change the VIEW_COMFY_FILE_NAME like you mentioned.

> But this can only load one json, can it load multiple jsons by default?
You can store multiple workflows_api in one view_comfy.json but it will not load multiple view_comfy.jsons.

let me know if you manage to solve this

**Comment by chinchaun** [comment]
closing this, feel free to ask more questions if you have @Jypope
