### ISSUE TITLE
No output files found

### ISSUE THREAD

**Issue by jeffreyrobeson** [ViewComfy/ViewComfy#50]
POST /api/comfy 500 in 40518ms
WebSocket connection opened
Executed: {
  node: '52',
  display_node: '52',
  output: { images: [ [Object], [Object], [Object], [Object] ] },
  prompt_id: '7f9203be-72ec-4b8c-bee6-9652e9ee5f57'
}
Failed to run the workflow
{
  error: ComfyWorkflowError {
    message: 'No output files found',
    errorType: 'ComfyWorkflowError',
    errors: [ 'No output files found' ]
  }
}

**Comment by jeffreyrobeson** [comment]
![image](https://github.com/user-attachments/assets/210ff2eb-818b-4725-b88d-5e0d8df1450a)

**Comment by jeffreyrobeson** [comment]
F:\ViewComfy>npm run dev

> viewcomfy@0.1.0 dev
> cross-env NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/80e9a452-ea6d-4932-85cb-0c928ea50159
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:9230/3d61922b-105b-48c3-bec1-95e38fdfa984
For help, see: https://nodejs.org/en/docs/inspector
   the --inspect option was detected, the Next.js router server should be inspected at port 9230.
  ▲ Next.js 14.2.11
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.1s
 ○ Compiling / ...
 ✓ Compiled / in 4.3s (1648 modules)
 GET / 200 in 4739ms
 ✓ Compiled in 507ms (800 modules)
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 1615ms (840 modules)
 GET /favicon.ico 200 in 1684ms
 ✓ Compiled /api/comfy in 318ms (849 modules)
WebSocket connection opened
Executed: {
  node: '52',
  display_node: '52',
  output: { images: [ [Object], [Object], [Object], [Object] ] },
  prompt_id: 'd4c80564-5358-4f11-be84-80f60fef2607'
}
Failed to run the workflow
{
  error: ComfyWorkflowError {
    message: 'No output files found',
    errorType: 'ComfyWorkflowError',
    errors: [ 'No output files found' ]
  }
}
 POST /api/comfy 500 in 53679ms

**Comment by chinchaun** [comment]
can you also share this workflow to test it out?

**Comment by chinchaun** [comment]
close with the lack of activity
