### ISSUE TITLE
 Can I specify any project to output, for example, only pictures will be output, and no text or other items will be output?

### ISSUE THREAD

**Issue by jeffreyrobeson** [ViewComfy/ViewComfy#53]
![5835865fd9fd793a09b20e17652ee662](https://github.com/user-attachments/assets/25938116-88c4-4e73-8a0a-2a31ee22bb95)

**Comment by GBieler** [comment]
Hey @jeffreyrobeson, ViewComfy will display all the assets that are returned by the ComfyUI API. 

For images and video, those assets are the ones saved in the ComfyUI repo's output folder. So, for example, if you don't want to show an image, you can use the preview image node instead of the save image node. 

And for text, the API only returns assets from a few predefined nodes. I don't know all of them, but for example, the show text node from LLM party will return text. 

Let me know if this addresses your concerns

**Comment by jeffreyrobeson** [comment]
I only want to output part of the second point in the picture above, and no other content is needed. How to achieve this?
[万物洗稿工作流BizyAir版2024112801.json](https://github.com/user-attachments/files/17966061/BizyAir.2024112801.json)

**Comment by jeffreyrobeson** [comment]
![image](https://github.com/user-attachments/assets/20b57faa-df75-44d5-8eaa-09b58d68d740)
How to prevent this part from being output？

**Comment by GBieler** [comment]
For some reason, that node returns a string to the API. Until we have a permanent solution, you could disable string outputs from being displayed by commenting out this code in playground-page.tsx (line 235 to 247):

                                                           {(output.outputs.type.startsWith('text/')) && (
                                                                <pre className="whitespace-pre-wrap break-words text-sm bg-white rounded-md w-full">
                                                                    {URL.createObjectURL(output.outputs) && (
                                                                        <object
                                                                            data={output.url}
                                                                            type={output.outputs.type}
                                                                            className="w-full"
                                                                        >
                                                                            Unable to display text content
                                                                        </object>
                                                                    )}
                                                                </pre>
                                                            )}

**Comment by chinchaun** [comment]
this should fix the error
