### ISSUE TITLE
How can I save multiple workflows on a web?

### ISSUE THREAD

**Issue by NagashiTTT** [ViewComfy/ViewComfy#54]
At present, it seems that each view_comfy.json can only correspond to one workflow. Is there a way to save multiple workflows for switching within the webpage?

**Comment by chinchaun** [comment]
hello @NagashiTTT, yes this is supported.

In the editor, you can upload a workflow, save the changes, and then you can keep uploading more workflows, save them again, and in the playground, you will have a dropdown to pick from

**Comment by chinchaun** [comment]
closing this with lack of activity

**Comment by NagashiTTT** [comment]
> closing this with lack of activity

Thank you for your guidance! I have solved this problem! Thank you very much.
