### ISSUE TITLE
Failed to launch ComfyUI

### ISSUE THREAD

**Issue by stone100010** [ViewComfy/ViewComfy#60]
libulibu@65f5a8ea8889:/home/workspace/ViewComfy$ COMFYUI_PORT=192.168.40.2:1036 npm run dev

> viewcomfy@0.1.0 dev
> cross-env NODE_OPTIONS='--inspect' next dev -H 0.0.0.0 -p 8188

Debugger listening on ws://127.0.0.1:9229/1282b193-7c2d-4259-843f-ce46a202a433
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:9230/2f4e45dd-0a13-4625-b544-897dd4ba324e
For help, see: https://nodejs.org/en/docs/inspector
   the --inspect option was detected, the Next.js router server should be inspected at port 9230.
  ▲ Next.js 14.2.11
  - Local:        http://localhost:8188
  - Network:      http://0.0.0.0:8188
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 10.9s
 ○ Compiling / ...
 ✓ Compiled / in 899ms (836 modules)
 GET / 200 in 1091ms
 ✓ Compiled /favicon.ico in 96ms (460 modules)
 ✓ Compiled (488 modules)
 GET /favicon.ico 200 in 184ms
 GET /api/playground 200 in 220ms
 GET /api/playground 200 in 4ms
 ✓ Compiled /api/comfy in 198ms (470 modules)
 ✓ Compiled /_not-found in 143ms (881 modules)
Failed to launch ComfyUI
{ stderr: '/bin/sh: 1: comfy: not found\n', stdout: '' }
 POST /api/comfy 500 in 514ms
 GET /history 404 in 254ms

**Comment by stone100010** [comment]
comfyui's services are on other devices: 192.168.40.2:1036

**Comment by stone100010** [comment]
The first setting is normal, a blank area I uploaded workflow_api.json, and then click create, failed, and then I close ViewComfy service, again execute the command "COMFYUI_PORT=192.168.40.2:1036 npm run dev", the interface does not return to the original blank area but directly jumped here, I do not know how to go back to the most initial blank area interface, the current interface screenshot is as follows:

![2024-12-18 20-34-41](https://github.com/user-attachments/assets/398727af-62b4-40f7-8595-085409210125)

**Comment by chinchaun** [comment]
hello @stone100010, how are you?
if your comfyui server is on another machine, the input images will not work for now, we're working on supporting running this feature.

In the 2nd case that your page is blank, did you set the variable NEXT_PUBLIC_VIEW_MODE to true?
ViewComfy will not store your editions between refreshes of the browser you need to download the view_comfy.json file and you can drop it and it will load again, if you have morquestions,ns we're very active in our discord

**Comment by stone100010** [comment]
I have come back, and now the situation is inside a docker container:
comfyui service started, 127.0.0.1: 300
node.js version v22.12.0
The file configuration under ViewComfy is as follows：
.env:

`COMFY_OUTPUT_DIR=""
WORKFLOW_API_FILE_NAME=""
VIEW_COMFY_FILE_NAME=""
VENV_ACTIVATION_PATH=""

# Public Variables
NEXT_PUBLIC_VIEW_MODE="false"
`
package.json partial content:
`
{
  "name": "viewcomfy",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_OPTIONS='--inspect' next dev -H 0.0.0.0 -p 7860",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
`
Detailed startup results are shown below：
![截图 2024-12-19 11-41-00](https://github.com/user-attachments/assets/3546d684-3e6d-42d3-8767-b05fb323204b)

![截图 2024-12-19 11-29-00](https://github.com/user-attachments/assets/72ddec69-a97e-4e39-8494-fc469a1f8431)

**Comment by stone100010** [comment]
Thank you very much for the help of the author team. All the above problems have been solved. Currently, we are trying to support comfyui deployment on different machines.
I also learned javascript, haha...

**Comment by chinchaun** [comment]
amazing! I'm happy that your problems got solved and feel free to drop any suggestions or feedback
