### ISSUE TITLE
I can't choose my input.

### ISSUE THREAD

**Issue by HKCLynn** [ViewComfy/ViewComfy#61]
Thank you very much for your contribution! I have some suggestions that I hope can make our use more convenient.

In this app, if I do not have the basic text input such as ***CLIP Text Encode (Prompt)***, the platform can't show the ***generate*** button. But sometimes I always use some other nodes such as ***Text Multiline*** to be my input. I think maybe we can choose our basic inputs rather than the platform forces the type of basic input. 

Sometimes the platform will show the output which we don't want to show. For example:if I use the ***Image To Base64*** node, the platform will show the  base64 string.
![image](https://github.com/user-attachments/assets/8e39c4ae-9401-482e-a973-a637781fbfa3)
![image](https://github.com/user-attachments/assets/edb2c4f4-c42e-4573-a6fb-cece0cf59834)
![image](https://github.com/user-attachments/assets/c6250cc4-fc53-490f-97d4-d2c12a96d74c)

**Comment by chinchaun** [comment]
Hello @HKCLynn, thank you very much for your kind words and feedback.

> In this app, if I do not have the basic text input such as CLIP Text Encode (Prompt), the platform can't show the generate button. But sometimes I always use some other nodes such as Text Multiline to be my input. I think maybe we can choose our basic inputs rather than the platform forces the type of basic input.
This is something that is in our roadmap and want to implement in the near future.


Now what you can do is click on `Download as ViewComfy JSON` open the view_comy.json and move the whole property from advanced_inputs to inputs, here is an example:

view_comfy.json
```
"workflows": [
  {
    viewComfyJSON: 
      inputs: [
      ]
      advanced_inputs: [
        {
                        "key": "6-CLIPTextEncode",
                        "title": "CLIP Text Encode (Prompt)",
                        "inputs": [
                            {
                                "key": "6-inputs-text",
                                "title": "CLIP Text Encode (Prompt)",
                                "value": "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,",
                                "helpText": "Helper Text",
                                "valueType": "long-text",
                                "placeholder": "CLIP Text Encode (Prompt)",
                                "validations": {
                                    "required": true
                                },
                                "workflowPath": [
                                    "6",
                                    "inputs",
                                    "text"
                                ]
                            }
                        ]
                    }
      ]
  }
]
```
becomes
```
"workflows": [
  {
    viewComfyJSON: 
      inputs: [
        {
                        "key": "6-CLIPTextEncode",
                        "title": "CLIP Text Encode (Prompt)",
                        "inputs": [
                            {
                                "key": "6-inputs-text",
                                "title": "CLIP Text Encode (Prompt)",
                                "value": "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,",
                                "helpText": "Helper Text",
                                "valueType": "long-text",
                                "placeholder": "CLIP Text Encode (Prompt)",
                                "validations": {
                                    "required": true
                                },
                                "workflowPath": [
                                    "6",
                                    "inputs",
                                    "text"
                                ]
                            }
                        ]
                    }
      ]
      advanced_inputs: [
      ]
  }
]
```

> Sometimes the platform will show the output which we don't want to show. For example:if I use the Image To Base64 node, the platform will show the base64 string.

This is going to be fixed in the next version of our deployment, here is the PR: #59

**Comment by HKCLynn** [comment]
Thanks very much!
