### ISSUE TITLE
Initial form editor

### ISSUE THREAD

**Issue by alesccc** [ViewComfy/ViewComfy#8]
Once you have view_comfy.json created, is it possible to load up form editor again for changes?

**Comment by chinchaun** [comment]
Hey @alesccc, yes, you can upload the view_comfy.json to edit it again, but you cannot add a field that you removed. We plan to support that in the future.
one thing you can do is edit it by hand,  if you open the view_comfy.json you can see that the structure is pretty simple, another workaround that you can do is to upload the workflow_api.json, download that as a view_comfy.json, and copy-paste the fields that you want to add to the view_comfy.json that you want to update. 
if you want I can help you with it in Discord

**Comment by alesccc** [comment]
Thanks @chinchaun :)
Thing is I am trying to swap to another workflow but I am not able to open the initial form editor now, unless I remove everything and reinstall viewcomfy again

**Comment by chinchaun** [comment]
@alesccc sure, let me know how it goes!
